name: 'Setup Environment'
description: 'Sets up the environment for building and deploying the Lambda function.'
runs:
  using: "composite"
  steps:
    - shell: bash
      working-directory: ${{ github.action_path }}/../../ 
      run: |
        make
          -C ${{ github.workspace }}/${{ inputs.lambda-path }} \
          -f ${{ github.action_path }}/../../makefiles/setup.mk \
          env-setup