name: 'Build Lambda'
description: 'Builds the Lambda function and prepares it for deployment.'
inputs:
  lambda-path:
    description: 'Ruta de la lambda en el proyecto (la carpeta que contiene el package.json y el código fuente).'
    required: true
    default: './app'

outputs:
  zip-path:
    description: 'Ruta donde quedó el zip'
    value: ${{ steps.run-make.outputs.zip_result }}

runs:
  using: 'composite'
  steps:
    - name: Run Centralized Makefile
      id: run-make
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        pwd
        ls -la
        # Usamos -f para apuntar al archivo de lógica en la carpeta central-logic
        # Pasamos PROJECT_DIR para asegurar que el zip se cree en el lugar correcto
        make -f central-logic/makefiles/fn.mk update.lambda \
             PROJECT_DIR=${{ inputs.lambda-path }}

        # Generamos el output para que la línea 12 de tu imagen funcione
        echo "zip_result=${{ inputs.lambda-path }}/dist/lambda.zip" >> $GITHUB_OUTPUT