name: 'Build Lambda'
description: 'Builds the Lambda function and prepares it for deployment.'

outputs:
  zip-path:
    description: 'Ruta donde quedó el zip'
    value: ${{ steps.run-make.outputs.zip_path }}

runs:
  using: 'composite'
  steps:
    - name: Run Centralized Makefile
      id: run-make
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        make -f workflow-core/makefiles/fn.mk update.lambda
        echo "zip-path=${PROJECT_DIR}/dist/${PROJECT_NAME}-${APP_ENV}.zip" >> $GITHUB_OUTPUT