name: 'Build Lambda'
description: 'Builds the Lambda function and prepares it for deployment.'
inputs:
  lambda-path:
    description: 'Ruta de la lambda en el proyecto (la carpeta que contiene el package.json y el código fuente).'
    required: true
    default: './app'

outputs:
  zip-path:
    description: 'Ruta donde quedó el zip'
    value: ${{ steps.run-make.outputs.zip_result }}

runs:
  using: 'composite'
  steps:
    - name: Run Centralized Makefile
      id: run-make
      shell: bash
      working-directory: ${{ github.workspace }}/central-logic/
      run: |
        make update.lambda 
        ls
        pwd
        cd ${{ github.workspace }}
        pwd
        ls -la
        cd ${{ github.workspace }}/central-logic
        pwd
        ls -la
        echo ${PROJECT_DIR}
        echo $PROJECT_DIR