---
name: PR Validation

on:
  workflow_call:

jobs:

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      
      - name: Setup Node & Cache
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './app/package-lock.json'

      - name: Install and Test
        working-directory: ./app 
        env:
          FORCE_COLOR: 1
        run: |
          npm ci
          npm test
  
  build:
    name: Install Dependencies And Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      
      - name: Setup Runtime
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './app/package-lock.json'
      
      - name: Build Application
        working-directory: ./app
        run: |
          npm ci
          npm run build

      - name: Post Run Link
        uses: mshick/add-pr-comment@v2
        if: always()
        with:
          message: |
            ### 🛠️ Resultado de la Validación
            - **Estado:** ${{ job.status == 'success' && '✅ Pasó' || '❌ Falló' }}
            - **Workflow:** [Ver ejecución del Pull Request](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})