---
name: Backend Lambda Feature CI (Soft GitFlow)

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      node_version:
        required: false
        default: "18"
        type: string
      aws_region:
        required: false
        default: "us-east-1"
        type: string
    # secrets:
    #   AWS_ROLE_ARN:
    #     required: true

env:
  STAGE: feature
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: test
        run: |
          pwd
          ls -la
          make dump-NPM_PACKAGE_NAME

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './app/package-lock.json'

      - name: Install dependencies
        working-directory: ./app
        run: ls -la && npm install

      - name: Build project
        working-directory: ./app
        run: npm run build && ls -la

      - name: Package Lambda
        working-directory: ./app
        run: |
          mkdir -p dist-package
          cp -r dist node_modules package.json dist-package/
          cd dist-package && zip -r ../lambda.zip .

      - name: Upload Artifact
        id: mi_zip
        uses: actions/upload-artifact@v5
        with:
          name: mi-lambda-zip
          path: app/lambda.zip
          retention-days: 1

      - name: Run base make
        uses: dvop-test/workflow-backend-lambda/actions/build-lambda@master

    outputs:
      artifact-name: ${{ steps.mi_zip.outputs.artifact-id }}