---
name: Backend Lambda Feature CI (Soft GitFlow)

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      node_version:
        required: false
        default: "18"
        type: string
      aws_region:
        required: false
        default: "us-east-1"
        type: string
    # secrets:
    #   AWS_ROLE_ARN:
    #     required: true

env:
  STAGE: feature
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.mi_zip.outputs.artifact-id }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5


      - name: Checkout Base Logic (Padre)
        uses: actions/checkout@v5
        with:
          repository: dvop-test/workflow-backend-lambda
          # IMPORTANTE: La ruta debe coincidir con tu 'include' (makefiles/fn.mk)
          path: repo-base

      - name: Run Makefile Target
        run: |
          ls -la
          # 1. Copiamos SOLO los archivos .mk del padre a la carpeta makefiles del hijo
          # Esto combina ambos contenidos en una sola carpeta
          cp repo-base/makefiles/*.mk ./makefiles/
          
          # 2. Verificamos que ahora estén todos juntos (los del hijo + fn.mk del padre)
          ls -la makefiles/
          
          # 3. Ahora el 'include makefiles/fn.mk' funcionará con todo el contexto
          make create.lambda

      - name: test
        run: |
          pwd
          ls -la
          make dump-NPM_PACKAGE_NAME

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './app/package-lock.json'

      - name: Install dependencies
        working-directory: ./app
        run: ls -la && npm install

      - name: Build project
        working-directory: ./app
        run: npm run build && ls -la

      - name: Run Makefile Target
        working-directory: ./app
        run: make create.lambda

      - name: Run base make
        id: base_make_step 
        uses: dvop-test/workflow-backend-lambda/actions/build-lambda@master
        with:
          lambda-path: 'app' # Enviamos la ruta al INPUT

      - name: Usar el resultado
        working-directory: ./app
        run: |
          echo "El Makefile guardó el archivo en: ${{ steps.base_make_step.outputs.zip-path }}"
          ls -la

      - name: Upload Artifact
        if: success()
        id: mi_zip
        uses: actions/upload-artifact@v5
        with:
          name: mi-lambda-zip
          path: ${{ steps.base_make_step.outputs.zip-path }}
          retention-days: 1