---
name: Backend Lambda Push CI (Soft GitFlow)

on:
  workflow_call:

jobs:

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Generate Live Link
        run: |
          echo "### 🚀 Seguimiento de Despliegue" >> $GITHUB_STEP_SUMMARY
          echo "El empaquetado y validación han comenzado." >> $GITHUB_STEP_SUMMARY
          echo "[Haz clic aquí para ver los logs en vivo](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY

      - name: Checkout Code
        uses: actions/checkout@v5
      
      - name: Install and Test
        working-directory: ./app 
        env:
          FORCE_COLOR: 1
        run: |
          npm ci
          npm test

  build:
    name: Build And Package
    needs: test
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.upload_lambda_zip.outputs.artifact-id }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Checkout CI/CD Core Logic
        uses: actions/checkout@v5
        with:
          repository: dvop-test/workflow-backend-lambda
          path: workflow-core

      - name: Setup Environment
        uses: dvop-test/workflow-backend-lambda/actions/setup-environment@master

      - name: Setup Runtime
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './app/package-lock.json'

      - name: Install Dependencies
        working-directory: ./app
        run: npm ci

      - name: Build Application
        working-directory: ./app
        run: npm run build

      - name: Package Lambda
        id: package_step 
        uses: dvop-test/workflow-backend-lambda/actions/build-lambda@master

      - name: Upload Artifact
        if: success()
        id: upload_lambda_zip
        uses: actions/upload-artifact@v5
        with:
          name: ${{ env.PROJECT_NAME }}-${{ env.APP_ENV }}
          path: ${{ steps.package_step.outputs.zip_path }}
          retention-days: 7