---
name: Backend Lambda Feature CI (Soft GitFlow)

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      node_version:
        required: false
        default: "18"
        type: string
      aws_region:
        required: false
        default: "us-east-1"
        type: string
    # secrets:
    #   AWS_ROLE_ARN:
    #     required: true

env:
  STAGE: feature

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    outputs:
      artifact-name: ${{ steps.artifact.outputs.name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Package Lambda
        run: |
          pwd
          ls
          mkdir -p dist-package
          cp -r dist node_modules package.json dist-package/
          cd dist-package && zip -r ../lambda.zip .

      - name: Upload artifact
        id: artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-artifact
          path: lambda.zip
